---
- hosts: jenkins-slave
  become: true
  tasks:
  - name: update ubuntu repo and cache
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: install java
    apt:
      name: openjdk-17-jdk
      state: present
  
  - name: download maven package
    get_url: 
      url: https://dlcdn.apache.org/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz
      dest:  /opt

  - name: extract maven package
    unarchive:
      src: /opt/apache-maven-3.9.11-bin.tar.gz
      dest: /opt
      remote_src: yes